# Generated by Django 4.1.5 on 2023-01-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_publication', '0017_auto_20211227_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='NAME',
            field=models.CharField(max_length=150),
        ),
    ]
